#define COLOR_NONE "\e[0m"

#define COLOR_RED "\e[31;1m"
#define COLOR_GREEN "\e[32;1m"
#define COLOR_YELLOW "\e[33;1m"
#define COLOR_BLUE "\e[34;1m"
#define COLOR_MAGENTA "\e[35;1m"
#define COLOR_CYAN "\e[36;11m"

#define COLOR_BRIGHT_RED "\e[91;1m"
#define COLOR_BRIGHT_GREEN "\e[92;1m"
#define COLOR_BRIGHT_YELLOW "\e[93;1m"
#define COLOR_BRIGHT_BLUE "\e[94;1m"
#define COLOR_BRIGHT_MAGENTA "\e[95;1m"
#define COLOR_BRIGHT_CYAN "\e[96;11m"
