#define COLOR_NONE "\e[0m"
#define COLOR_RED "\e[91;1m"
#define COLOR_GREEN "\e[92;1m"
#define COLOR_YELLOW "\e[93;1m"
#define COLOR_BLUE "\e[94;1m"
#define COLOR_MAGENTA "\e[95;1m"
#define COLOR_CYAN "\e[96;11m"
